# ─── Database ───────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/agribuddy_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=8de15f8db3f3639669d21412486264d10f79d03f6531a5aa6c6a4001d1ac6ed0
jwt.expiration.ms=86400000

# ─── Server Port ─────────────────────────────────
server.port=8080

# ─── Email (Gmail SMTP for OTP) ──────────────────
# IMPORTANT: Use an App Password, NOT your real Gmail password
# Steps to get App Password:
# 1. Go to myaccount.google.com
# 2. Security → 2-Step Verification → App passwords
# 3. Generate password for "Mail"
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shriyashjagdale1@gmail.com
spring.mail.password=uyjmyjwfrohksggl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true